modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[dependencies.projectecho]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectecho]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="projectecho"
version="1.0.0"
displayName="Project: Echo"
description='''
A haunting presence roams your world.
NULL_POINTER watches. NULL_POINTER repairs.
Will you help it... or destroy it?
'''
